name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Demo
        run: echo "java project"

      - name: Build image docker
        run : docker build -t demo-core-nlp:latest .

      - name: Verify image docker
        run: docker images

  Scan-vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - name: Install trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y
          trivy --version

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin
          grype version

      - name: Scan image docker with Trivy
        run: trivy demo-core-nlp:latest

      - name: Scan image docker with Grype
        run: grype demo-core-nlp:latest

      - name: Scan Project with Trivy and Generate Report
        id: trivy_scan
        run: trivy . --format json --output trivy-report.json

      - name: Upload Trivy Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-security-report
          path: trivy-report.json
          retention-days: 7

      - name: Scan Docker Image with Grype and Generate Report
        id: grype_scan
        run: grype demo-nlp:latest --scope all-layers --output json > grype-report.json

      - name: Upload Grype Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grype-security-report
          path: grype-report.json
          retention-days: 7

  Scan-code:
    runs-on: ubuntu-latest
    steps:
      - name: SonarQube Scan (Placeholder)
        run: echo "SonarQube Scan"

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploy"